# Generated by Django 3.2.6 on 2021-09-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='dias_sem_resposta',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_envio',
            field=models.DateField(db_index=True, verbose_name='Data de envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_resposta',
            field=models.DateField(db_index=True, verbose_name='Data de resposta'),
        ),
    ]
