# Generated by Django 3.2.6 on 2021-09-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=50, verbose_name='Sigla')),
                ('esfera_orgao', models.CharField(choices=[('municipal', 'MUNICIPAL'), ('estadual', 'ESTADUAL'), ('federal', 'FEDERAL')], max_length=20, verbose_name='Esfera')),
                ('site', models.URLField(blank=True, max_length=50, verbose_name='Site')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Informações adicionais sobre o órgão')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='esfera',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.orgao'),
        ),
    ]
