# Generated by Django 3.2.6 on 2021-09-27 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_esfera_orgao_orgao_esfera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(db_index=True, verbose_name='Data de criação')),
                ('data_conclusao', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de conclusão')),
                ('meio_contato', models.CharField(max_length=200, verbose_name='Meio de Contato')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('historico', models.TextField(blank=True, null=True, verbose_name='Historico')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('arquivo', models.TextField(blank=True, null=True, verbose_name='Arquivo')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.orgao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido')),
            ],
        ),
    ]
