# Generated by Django 3.2.6 on 2021-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20210927_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(blank=True, choices=[('nova', 'NOVA'), ('em_andamento', 'EM ANDAMENTO'), ('deferida', 'DEFERIDA'), ('indeferida', 'INDEFERIDA'), ('arquivada', 'ARQUIVADA')], max_length=50, verbose_name='Status'),
        ),
    ]
