# Generated by Django 3.2.8 on 2021-11-22 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("initials", models.CharField(max_length=50, verbose_name="Sigla")),
                (
                    "sphere",
                    models.CharField(
                        choices=[
                            ("municipal", "MUNICIPAL"),
                            ("estadual", "ESTADUAL"),
                            ("federal", "FEDERAL"),
                        ],
                        max_length=20,
                        verbose_name="Esfera",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=50, verbose_name="Site"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telephone_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone"
                    ),
                ),
                (
                    "extra_information",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Informações adicionais sobre o órgão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Órgão",
                "verbose_name_plural": "Órgãos",
            },
        ),
        migrations.CreateModel(
            name="InformationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "num_protocol",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Número de Protocolo"
                    ),
                ),
                (
                    "sent_at",
                    models.DateField(db_index=True, verbose_name="Data de envio"),
                ),
                (
                    "replied_at",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Data de resposta",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Título do Pedido"),
                ),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Meio de Contato"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sem_resposta", "SEM RESPOSTA"),
                            ("respondido_parcialmente", "RESPONDIDO PARCIALMENTE"),
                            ("respondido", "RESPONDIDO"),
                            ("respondido_apos_recurso", "RESPONDIDO APÓS RECURSO"),
                            ("em_recurso", "EM RECURSO"),
                            ("em_andamento", "EM ANDAMENTO"),
                            ("respondido_com_atraso", "RESPONDIDO COM ATRASO"),
                            ("pedido_nao_processado", "PEDIDO NÃO PROCESSADO"),
                        ],
                        max_length=50,
                        verbose_name="Status do Pedido",
                    ),
                ),
                (
                    "historic",
                    models.TextField(blank=True, null=True, verbose_name="Histórico"),
                ),
                ("text", models.TextField(verbose_name="Texto")),
                (
                    "reply",
                    models.TextField(blank=True, null=True, verbose_name="Resposta"),
                ),
                (
                    "public_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="information_requests.publicagency",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "registered_at",
                    models.DateField(
                        db_index=True, verbose_name="Data de registro da denúncia"
                    ),
                ),
                (
                    "finished_at",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Data de conclusão",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Meio de Contato"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nova", "NOVA"),
                            ("em_andamento", "EM ANDAMENTO"),
                            ("deferida", "DEFERIDA"),
                            ("indeferida", "INDEFERIDA"),
                            ("arquivada", "ARQUIVADA"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texto")),
                (
                    "historic",
                    models.TextField(blank=True, null=True, verbose_name="Histórico"),
                ),
                (
                    "reply",
                    models.TextField(blank=True, null=True, verbose_name="Resposta"),
                ),
                (
                    "extra_information",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observações adicionais da denúncia",
                    ),
                ),
                (
                    "information_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="information_requests.informationrequest",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "public_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="information_requests.publicagency",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
            },
        ),
    ]
