# Generated by Django 3.2.8 on 2021-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='informationrequest',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título do Pedido'),
        ),
        migrations.AlterField(
            model_name='publicagency',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
